<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\SportCategory;

class LapanganSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $futsal = SportCategory::where('slug', 'futsal')->first();
        $basket = SportCategory::where('slug', 'basket')->first();
        $tenis = SportCategory::where('slug', 'tenis')->first();
        $badminton = SportCategory::where('slug', 'badminton')->first();
        $voli = SportCategory::where('slug', 'voli')->first();
        $padel = SportCategory::where('slug', 'padel')->first();

        DB::table('lapangan')->insert([
            // FUTSAL
            [
                'sport_category_id' => $futsal->id,
                'nama' => 'Malang Futsal Arena Premium',
                'kode_lapangan' => 'FTS-001',
                'deskripsi' => 'Lapangan futsal indoor premium dengan rumput sintetis import, sistem pencahayaan LED, dan AC. Cocok untuk pertandingan profesional maupun latihan tim.',
                'tipe' => 'indoor',
                'lokasi' => 'Lantai 2, Mall Olympic Garden',
                'kota' => 'Malang',
                'alamat' => 'Jl. MT. Haryono No. 167, Malang',
                'harga_per_jam' => 180000,
                'harga_weekend' => 220000,
                'foto' => 'https://placehold.co/800x500/2ecc71/ffffff?text=Malang+Futsal+Arena',
                'galeri' => json_encode([
                    'https://placehold.co/800x500/2ecc71/ffffff?text=Lapangan+1',
                    'https://placehold.co/800x500/27ae60/ffffff?text=Lapangan+2',
                    'https://placehold.co/800x500/16a085/ffffff?text=Fasilitas'
                ]),
                'fasilitas' => json_encode(['AC', 'Kantin', 'Parkir Luas', 'Toilet', 'Mushola', 'Ruang Ganti', 'WiFi']),
                'kapasitas' => 14,
                'ukuran' => '40m x 20m',
                'aturan' => 'Sepatu futsal wajib, dilarang merokok di area lapangan',
                'jumlah_lapangan' => 3,
                'tersedia' => true,
                'rating' => 5,
                'jumlah_review' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sport_category_id' => $futsal->id,
                'nama' => 'Dinoyo Futsal Center',
                'kode_lapangan' => 'FTS-002',
                'deskripsi' => 'Futsal center dengan 4 lapangan berkualitas di area Dinoyo. Fasilitas lengkap dan harga terjangkau untuk mahasiswa.',
                'tipe' => 'indoor',
                'lokasi' => 'Kompleks Olahraga Dinoyo',
                'kota' => 'Malang',
                'alamat' => 'Jl. MT. Haryono, Dinoyo, Malang',
                'harga_per_jam' => 120000,
                'harga_weekend' => 150000,
                'foto' => 'https://placehold.co/800x500/2ecc71/ffffff?text=Dinoyo+Futsal',
                'galeri' => json_encode([
                    'https://placehold.co/800x500/2ecc71/ffffff?text=Court+1',
                    'https://placehold.co/800x500/27ae60/ffffff?text=Court+2'
                ]),
                'fasilitas' => json_encode(['Kantin', 'Parkir', 'Toilet', 'Mushola', 'Tribun']),
                'kapasitas' => 14,
                'ukuran' => '38m x 18m',
                'aturan' => 'Sepatu futsal wajib, booking minimal 1 jam',
                'jumlah_lapangan' => 4,
                'tersedia' => true,
                'rating' => 4,
                'jumlah_review' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sport_category_id' => $futsal->id,
                'nama' => 'Batu Futsal Park',
                'kode_lapangan' => 'FTS-003',
                'deskripsi' => 'Lapangan futsal outdoor dengan view pegunungan Batu yang indah. Udara sejuk dan fasilitas memadai.',
                'tipe' => 'outdoor',
                'lokasi' => 'Kawasan Wisata Batu',
                'kota' => 'Batu',
                'alamat' => 'Jl. Raya Selecta No. 1, Batu',
                'harga_per_jam' => 100000,
                'harga_weekend' => 130000,
                'foto' => 'https://placehold.co/800x500/16a085/ffffff?text=Batu+Futsal+Park',
                'galeri' => json_encode([
                    'https://placehold.co/800x500/16a085/ffffff?text=Outdoor+Court',
                    'https://placehold.co/800x500/1abc9c/ffffff?text=Mountain+View'
                ]),
                'fasilitas' => json_encode(['Kantin', 'Parkir', 'Toilet', 'Gazebo']),
                'kapasitas' => 14,
                'ukuran' => '40m x 20m',
                'aturan' => 'Sepatu futsal wajib, jaga kebersihan',
                'jumlah_lapangan' => 2,
                'tersedia' => true,
                'rating' => 4,
                'jumlah_review' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // BASKET
            [
                'sport_category_id' => $basket->id,
                'nama' => 'Surabaya Basketball Hall',
                'kode_lapangan' => 'BSK-001',
                'deskripsi' => 'Lapangan basket indoor standar nasional dengan lantai parket berkualitas tinggi. Tempat favorit komunitas basket Surabaya.',
                'tipe' => 'indoor',
                'lokasi' => 'GOR Pancasila',
                'kota' => 'Surabaya',
                'alamat' => 'Jl. Gubernur Suryo, Surabaya',
                'harga_per_jam' => 200000,
                'harga_weekend' => 250000,
                'foto' => 'https://placehold.co/800x500/e74c3c/ffffff?text=Surabaya+Basketball',
                'galeri' => json_encode([
                    'https://placehold.co/800x500/e74c3c/ffffff?text=Indoor+Court',
                    'https://placehold.co/800x500/c0392b/ffffff?text=Full+Court'
                ]),
                'fasilitas' => json_encode(['AC', 'Kantin', 'Parkir Luas', 'Toilet', 'Mushola', 'Ruang Ganti', 'Tribun']),
                'kapasitas' => 20,
                'ukuran' => '28m x 15m',
                'aturan' => 'Sepatu basket wajib, tidak boleh pakai sepatu outdoor',
                'jumlah_lapangan' => 2,
                'tersedia' => true,
                'rating' => 5,
                'jumlah_review' => 67,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sport_category_id' => $basket->id,
                'nama' => 'Malang Streetball Arena',
                'kode_lapangan' => 'BSK-002',
                'deskripsi' => 'Lapangan basket outdoor dengan permukaan rubber berkualitas. Cocok untuk streetball dan latihan casual.',
                'tipe' => 'outdoor',
                'lokasi' => 'Taman Rekreasi Senaputra',
                'kota' => 'Malang',
                'alamat' => 'Jl. Galunggung, Malang',
                'harga_per_jam' => 80000,
                'harga_weekend' => 100000,
                'foto' => 'https://placehold.co/800x500/e67e22/ffffff?text=Streetball+Arena',
                'galeri' => json_encode([
                    'https://placehold.co/800x500/e67e22/ffffff?text=Outdoor+Court',
                    'https://placehold.co/800x500/d35400/ffffff?text=Half+Court'
                ]),
                'fasilitas' => json_encode(['Parkir', 'Toilet', 'Kantin', 'Tribun']),
                'kapasitas' => 20,
                'ukuran' => '28m x 15m',
                'aturan' => 'Sepatu olahraga wajib',
                'jumlah_lapangan' => 3,
                'tersedia' => true,
                'rating' => 4,
                'jumlah_review' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // TENIS
            [
                'sport_category_id' => $tenis->id,
                'nama' => 'Malang Tennis Club',
                'kode_lapangan' => 'TNS-001',
                'deskripsi' => 'Kompleks tenis outdoor dengan 5 lapangan hard court standar nasional. Tempat favorit komunitas tenis Malang.',
                'tipe' => 'outdoor',
                'lokasi' => 'Kompleks Tennis Sawojajar',
                'kota' => 'Malang',
                'alamat' => 'Jl. Danau Sentani, Sawojajar, Malang',
                'harga_per_jam' => 75000,
                'harga_weekend' => 100000,
                'foto' => 'https://placehold.co/800x500/f39c12/ffffff?text=Malang+Tennis+Club',
                'galeri' => json_encode([
                    'https://placehold.co/800x500/f39c12/ffffff?text=Hard+Court',
                    'https://placehold.co/800x500/e67e22/ffffff?text=5+Courts'
                ]),
                'fasilitas' => json_encode(['Parkir', 'Toilet', 'Kantin', 'Tribun Penonton', 'Rental Raket']),
                'kapasitas' => 4,
                'ukuran' => '23.77m x 10.97m',
                'aturan' => 'Sepatu tenis wajib, booking minimal 1 jam',
                'jumlah_lapangan' => 5,
                'tersedia' => true,
                'rating' => 4,
                'jumlah_review' => 56,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sport_category_id' => $tenis->id,
                'nama' => 'Surabaya Tennis Arena Indoor',
                'kode_lapangan' => 'TNS-002',
                'deskripsi' => 'Lapangan tenis indoor dengan AC dan pencahayaan LED sempurna. Cocok untuk turnamen dan latihan intensif.',
                'tipe' => 'indoor',
                'lokasi' => 'Tennis Indoor Complex',
                'kota' => 'Surabaya',
                'alamat' => 'Jl. HR Muhammad, Surabaya',
                'harga_per_jam' => 150000,
                'harga_weekend' => 180000,
                'foto' => 'https://placehold.co/800x500/e74c3c/ffffff?text=Indoor+Tennis',
                'galeri' => json_encode([
                    'https://placehold.co/800x500/e74c3c/ffffff?text=Court+1',
                    'https://placehold.co/800x500/c0392b/ffffff?text=AC+Room'
                ]),
                'fasilitas' => json_encode(['AC', 'Parkir', 'Toilet', 'Kantin', 'Ruang Ganti', 'Loker', 'Rental Raket']),
                'kapasitas' => 4,
                'ukuran' => '23.77m x 10.97m',
                'aturan' => 'Sepatu tenis wajib, dilarang minum di area permainan',
                'jumlah_lapangan' => 2,
                'tersedia' => true,
                'rating' => 5,
                'jumlah_review' => 41,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // BADMINTON
            [
                'sport_category_id' => $badminton->id,
                'nama' => 'Araya Badminton Hall',
                'kode_lapangan' => 'BDM-001',
                'deskripsi' => 'Lapangan badminton indoor dengan 8 court vinyl berkualitas tinggi dan pencahayaan LED. Venue turnamen resmi.',
                'tipe' => 'indoor',
                'lokasi' => 'GOR Araya',
                'kota' => 'Malang',
                'alamat' => 'Jl. Raya Langsep, Malang',
                'harga_per_jam' => 50000,
                'harga_weekend' => 70000,
                'foto' => 'https://placehold.co/800x500/9b59b6/ffffff?text=Araya+Badminton',
                'galeri' => json_encode([
                    'https://placehold.co/800x500/9b59b6/ffffff?text=8+Courts',
                    'https://placehold.co/800x500/8e44ad/ffffff?text=Indoor+Hall'
                ]),
                'fasilitas' => json_encode(['AC', 'Parkir Luas', 'Toilet', 'Kantin', 'Ruang Ganti', 'Rental Raket', 'Tribun']),
                'kapasitas' => 4,
                'ukuran' => '13.4m x 6.1m',
                'aturan' => 'Sepatu olahraga wajib, dilarang merokok',
                'jumlah_lapangan' => 8,
                'tersedia' => true,
                'rating' => 5,
                'jumlah_review' => 89,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sport_category_id' => $badminton->id,
                'nama' => 'Dinoyo Badminton Center',
                'kode_lapangan' => 'BDM-002',
                'deskripsi' => 'Lapangan badminton indoor dengan harga terjangkau, cocok untuk mahasiswa dan pemain casual.',
                'tipe' => 'indoor',
                'lokasi' => 'Area Dinoyo',
                'kota' => 'Malang',
                'alamat' => 'Jl. MT Haryono, Dinoyo, Malang',
                'harga_per_jam' => 35000,
                'harga_weekend' => 45000,
                'foto' => 'https://placehold.co/800x500/9b59b6/ffffff?text=Dinoyo+Badminton',
                'galeri' => json_encode([
                    'https://placehold.co/800x500/9b59b6/ffffff?text=Court+View',
                    'https://placehold.co/800x500/8e44ad/ffffff?text=Facility'
                ]),
                'fasilitas' => json_encode(['Parkir', 'Toilet', 'Kantin', 'Rental Raket']),
                'kapasitas' => 4,
                'ukuran' => '13.4m x 6.1m',
                'aturan' => 'Sepatu olahraga wajib',
                'jumlah_lapangan' => 5,
                'tersedia' => true,
                'rating' => 4,
                'jumlah_review' => 62,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // VOLI
            [
                'sport_category_id' => $voli->id,
                'nama' => 'GOR Gajayana Volleyball',
                'kode_lapangan' => 'VLI-001',
                'deskripsi' => 'Lapangan voli indoor standar nasional dengan lantai parket dan net resmi. Sering dipakai untuk kejuaraan.',
                'tipe' => 'indoor',
                'lokasi' => 'GOR Gajayana',
                'kota' => 'Malang',
                'alamat' => 'Jl. Gajayana, Malang',
                'harga_per_jam' => 150000,
                'harga_weekend' => 180000,
                'foto' => 'https://placehold.co/800x500/3498db/ffffff?text=Gajayana+Volleyball',
                'galeri' => json_encode([
                    'https://placehold.co/800x500/3498db/ffffff?text=Indoor+Court',
                    'https://placehold.co/800x500/2980b9/ffffff?text=Full+Hall'
                ]),
                'fasilitas' => json_encode(['AC', 'Parkir Luas', 'Toilet', 'Kantin', 'Ruang Ganti', 'Tribun', 'Sound System']),
                'kapasitas' => 18,
                'ukuran' => '18m x 9m',
                'aturan' => 'Sepatu voli wajib, maksimal 12 pemain per pertandingan',
                'jumlah_lapangan' => 2,
                'tersedia' => true,
                'rating' => 5,
                'jumlah_review' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sport_category_id' => $voli->id,
                'nama' => 'Pasir Putih Beach Volleyball',
                'kode_lapangan' => 'VLI-002',
                'deskripsi' => 'Lapangan beach volleyball outdoor dengan pasir berkualitas di kawasan wisata Pasir Putih.',
                'tipe' => 'outdoor',
                'lokasi' => 'Pantai Pasir Putih',
                'kota' => 'Pasuruan',
                'alamat' => 'Kawasan Wisata Pasir Putih, Pasuruan',
                'harga_per_jam' => 80000,
                'harga_weekend' => 100000,
                'foto' => 'https://placehold.co/800x500/1abc9c/ffffff?text=Beach+Volleyball',
                'galeri' => json_encode([
                    'https://placehold.co/800x500/1abc9c/ffffff?text=Beach+Court',
                    'https://placehold.co/800x500/16a085/ffffff?text=Ocean+View'
                ]),
                'fasilitas' => json_encode(['Parkir', 'Toilet', 'Shower', 'Warung', 'Gazebo']),
                'kapasitas' => 8,
                'ukuran' => '16m x 8m',
                'aturan' => 'Barefoot atau sandal pantai, jaga kebersihan pantai',
                'jumlah_lapangan' => 3,
                'tersedia' => true,
                'rating' => 4,
                'jumlah_review' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // MINI SOCCER
            [
                'sport_category_id' => SportCategory::where('slug', 'mini-soccer')->first()->id,
                'nama' => 'Singosari Mini Soccer Field',
                'kode_lapangan' => 'MSC-001',
                'deskripsi' => 'Lapangan mini soccer rumput sintetis di kawasan Singosari. Cocok untuk pertandingan 7vs7 dan latihan tim.',
                'tipe' => 'outdoor',
                'lokasi' => 'Singosari Sport Complex',
                'kota' => 'Malang',
                'alamat' => 'Jl. Raya Singosari, Singosari, Malang',
                'harga_per_jam' => 200000,
                'harga_weekend' => 250000,
                'foto' => 'https://placehold.co/800x500/27ae60/ffffff?text=Singosari+Mini+Soccer',
                'galeri' => json_encode([
                    'https://placehold.co/800x500/27ae60/ffffff?text=Field+View',
                    'https://placehold.co/800x500/2ecc71/ffffff?text=Night+Game',
                    'https://placehold.co/800x500/16a085/ffffff?text=Facility'
                ]),
                'fasilitas' => json_encode(['Parkir Luas', 'Toilet', 'Mushola', 'Kantin', 'Tribun', 'Lampu Sorot']),
                'kapasitas' => 16,
                'ukuran' => '60m x 40m',
                'aturan' => 'Sepatu bola wajib, dilarang menggunakan sepatu takon besi',
                'jumlah_lapangan' => 2,
                'tersedia' => true,
                'rating' => 4,
                'jumlah_review' => 52,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sport_category_id' => SportCategory::where('slug', 'mini-soccer')->first()->id,
                'nama' => 'Lawang Mini Soccer Arena',
                'kode_lapangan' => 'MSC-002',
                'deskripsi' => 'Arena mini soccer dengan 3 lapangan berkualitas. View pegunungan yang indah dan udara sejuk khas Lawang.',
                'tipe' => 'outdoor',
                'lokasi' => 'Lawang Sport Center',
                'kota' => 'Lawang',
                'alamat' => 'Jl. Raya Lawang No. 88, Lawang',
                'harga_per_jam' => 180000,
                'harga_weekend' => 220000,
                'foto' => 'https://placehold.co/800x500/2ecc71/ffffff?text=Lawang+Soccer+Arena',
                'galeri' => json_encode([
                    'https://placehold.co/800x500/2ecc71/ffffff?text=3+Fields',
                    'https://placehold.co/800x500/27ae60/ffffff?text=Mountain+View'
                ]),
                'fasilitas' => json_encode(['Parkir', 'Toilet', 'Mushola', 'Warung', 'Gazebo', 'Lampu Sorot']),
                'kapasitas' => 16,
                'ukuran' => '60m x 40m',
                'aturan' => 'Sepatu bola wajib, booking minimal 2 jam',
                'jumlah_lapangan' => 3,
                'tersedia' => true,
                'rating' => 5,
                'jumlah_review' => 38,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sport_category_id' => SportCategory::where('slug', 'mini-soccer')->first()->id,
                'nama' => 'Kepanjen Soccer Park',
                'kode_lapangan' => 'MSC-003',
                'deskripsi' => 'Lapangan mini soccer modern dengan rumput sintetis import dan fasilitas lengkap di Kepanjen.',
                'tipe' => 'outdoor',
                'lokasi' => 'Kepanjen Sports Complex',
                'kota' => 'Kepanjen',
                'alamat' => 'Jl. Raya Kepanjen, Malang',
                'harga_per_jam' => 150000,
                'harga_weekend' => 180000,
                'foto' => 'https://placehold.co/800x500/16a085/ffffff?text=Kepanjen+Soccer',
                'galeri' => json_encode([
                    'https://placehold.co/800x500/16a085/ffffff?text=Field+1',
                    'https://placehold.co/800x500/1abc9c/ffffff?text=Night+View'
                ]),
                'fasilitas' => json_encode(['Parkir', 'Toilet', 'Kantin', 'Lampu Sorot', 'Tribun']),
                'kapasitas' => 16,
                'ukuran' => '55m x 35m',
                'aturan' => 'Sepatu bola wajib, dilarang merokok di area lapangan',
                'jumlah_lapangan' => 2,
                'tersedia' => true,
                'rating' => 4,
                'jumlah_review' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // PADEL
            [
                'sport_category_id' => $padel->id,
                'nama' => 'Surabaya Padel Club',
                'kode_lapangan' => 'PDL-001',
                'deskripsi' => 'Lapangan padel tennis indoor pertama di Surabaya dengan dinding kaca dan rumput sintetis premium dari Spanyol.',
                'tipe' => 'indoor',
                'lokasi' => 'Pakuwon City Mall',
                'kota' => 'Surabaya',
                'alamat' => 'Pakuwon City Mall Lt. 3, Surabaya',
                'harga_per_jam' => 300000,
                'harga_weekend' => 350000,
                'foto' => 'https://placehold.co/800x500/e67e22/ffffff?text=Padel+Club',
                'galeri' => json_encode([
                    'https://placehold.co/800x500/e67e22/ffffff?text=Padel+Court',
                    'https://placehold.co/800x500/d35400/ffffff?text=Indoor+Arena'
                ]),
                'fasilitas' => json_encode(['AC', 'Parkir Mall', 'Cafe', 'Toilet', 'Ruang Ganti', 'Loker', 'Rental Raket', 'Pro Shop']),
                'kapasitas' => 4,
                'ukuran' => '20m x 10m',
                'aturan' => 'Sepatu padel atau tenis wajib, booking minimal 1.5 jam',
                'jumlah_lapangan' => 2,
                'tersedia' => true,
                'rating' => 5,
                'jumlah_review' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
